### PR TITLE
Ticket307 integrate travis.0

### PR DESCRIPTION
**Pull request by ebfull**
This is a working travis integration build which mimics our existing test suite build options. It's rebased on top of libzerocash's new master. There are a few issues:
- The tests are taking too long and might time out. We'll have to come up with some way to improve on it, maybe with caching, but I won't have luck until this is merged into something. (Travis won't save the cache until then.) Further, we could parallelize the tests with a build matrix, but I have no experience with using those with Travis and I'm not sure if it will just duplicate the entire build or not. (Some tips here would be great.)
- @defuse [notes](https://github.com/Electric-Coin-Company/libzerocash/pull/2#commitcomment-13755854) about the header files, but I can deal with this problem during the integration of this new branch downstream.
- see ticket 319
- merkleTest has been failing but apparently this is unrelated.

That being said it all builds and the tests at least execute before it times out!

### CODE REVIEW

**Comment by ebfull** [comment]
It builds and can run the tests (yay!) but they can't complete due to time restrictions.

**Comment by tromer** [comment]
How many cores do we get on Travis? Enabling `MULTICORE=1` in libsnark and libzerocash may help. The latter seems broken, though (e.g., missing `-fopenmp`).

**Comment by ebfull** [comment]
I'm not sure what Travis gives us, doesn't say in the build information. I can try enabling multicore but I'll have to take a note of it since we do not have that enabled downstream.

I think it actually might be best to run these in parallel:

```
    test_zerocash_pour_ppzksnark<default_r1cs_ppzksnark_pp>(2, 2, 4);
    test_zerocash_pour_ppzksnark<default_r1cs_ppzksnark_pp>(2, 3, 4);
    test_zerocash_pour_ppzksnark<default_r1cs_ppzksnark_pp>(3, 2, 4);
    test_zerocash_pour_ppzksnark<default_r1cs_ppzksnark_pp>(3, 3, 4);
    test_zerocash_pour_ppzksnark<default_r1cs_ppzksnark_pp>(2, 2, 32);
```

**Comment by defuse** [comment]
I read somewhere like half an hour ago that Travis has "1.5 cores." I don't know what that means and I can't find the place I read it.

IIRC, Travis only times out when the build/test hasn't generated output after a certain number of minutes. Maybe the solution is just to make sure that long test is always generating output periodically?

**Comment by ebfull** [comment]
Sadly it times out after 50 minutes _or_ 10 minutes of no output. We're running into the former issue. :(

**Comment by defuse** [comment]
Darn. :( 50 minutes is a pretty optimistic assumption. I wonder if we can get more since we're a paying customer?

**Comment by defuse** [comment]
I wonder why some of my commits are showing up in the commit list in this PR

**Comment by ebfull** [comment]
Nathan might have to chime in, but because this is a public repository it does not use our paying account. Or something.

**Comment by defuse** [comment]
Oh, when I renamed `zc.latest` I screwed up and blew away the commits I merged.

**Comment by ebfull** [comment]
Hmmm. Actually upstream libzerocash made some changes to the `.gitignore` file. I rebased on top of that, bringing your commits with me. Thus I am merging into a new branch (`zc.0ae3c6.latest`) instead of the branch you created (`zc.89aded7b.latest`).

**Comment by defuse** [comment]
Ahh, I see.

**Comment by defuse** [comment]
LGTM.

**Comment by ebfull** [comment]
It looks like this is good to merge and begin integration, but I want to address the testing speed issue first before I do that.

**Comment by ebfull** [comment]
Superseded by #5

**Pull request closed without merging**
