### PR TITLE
zc.latest.0.ticket391.merkle-tree-improvements.0

### PR DESCRIPTION
**Pull request by defuse**
ref: https://github.com/Electric-Coin-Company/zerocashd/issues/391

Misc fixes and improvements (feel free to pick and choose).

**Edit:** @nathan-at-least added ticket cross-link

### CODE REVIEW

**Comment by defuse** [comment]
Note that the title of this PR is misleading. It has nothing to do with Merkle trees.

**Comment by defuse** [comment]
Before merging `git cherry-pick` this: https://github.com/Zerocash/libzerocash/commit/9f5c80b55e253d235573919671d8aa39f884f2d3

**Comment by nathan-at-least** [comment]
Is this a followup to PR #20? They both reference https://github.com/Electric-Coin-Company/zerocashd/issues/391.

**Comment by defuse** [comment]
@nathan-at-least: Unfortunately the branch name on this PR is wrong, since I started out doing one thing, but ended up doing everything else I wanted to do on this branch (rather than creating PRs for each of the 15-20 independent changes).

**Pull request merged**
