### PR TITLE
zc.latest.0.ticket391.fix-merkle-compact-representation.0

### PR DESCRIPTION
**Pull request by defuse**
ref: https://github.com/Electric-Coin-Company/zerocashd/issues/391

**Edit:** crosslinked by @nathan-at-least

### CODE REVIEW

**Comment by defuse** [comment]
Oops, there are a bunch of XXX comments I didn't intend to include, but now that I think about it, it's probably better if those observations are recorded somewhere permanent. If the reviewers don't like them I'll rebase and get rid of them.

**Comment by defuse** [comment]
Note that the `testRootConsistencyZeroValues` test fails because the two implementations of merkle trees aren't completely compatible with each other yet. We should open a ticket about that, but I propose we resolve it by deleting the `MerkleTree` implementation: nothing uses it.

**Comment by ebfull** [comment]
We should try to land this fix before we unify protects and pours because that unification uses some incremental merkle tree stuff. (Though this commit likely doesn't touch that logic.)

**Comment by ebfull** [comment]
I think removing the MerkleTree is probably the best route. I don't imagine we need it for anything. Certainly not even for keeping paths in the tree up to date -- if we do, we can just modify the IncrementalMerkleTree to be more expressive.

**Comment by defuse** [comment]
The buildbot build broke for some reason:

http://ci.leastauthority.com:8010/builders/libzerocash/builds/92/steps/make

It really doesn't seem related to these changes.

**Comment by defuse** [comment]
The only argument I can see for keeping the MerkleTree is that it's another implementation that can be tested against. But if we're keeping another implementation for that reason alone, then I'd rather have a third-party one, either the one Sean made in rust, or one written by someone outside the company.

**Comment by ebfull** [comment]
LGTM

**Pull request merged**
