### PR TITLE
Use a build matrix to parallelize our pour test

### PR DESCRIPTION
**Pull request by ebfull**

### CODE REVIEW

**Comment by ebfull** [comment]
Just as I feared, it makes a new build for every single one instead of splitting the work. This will probably increase the chance of the build breaking since the compiler seems to get force killed by travis constantly.

**Comment by ebfull** [comment]
Why is travis just killing these build tasks? Why does it hate me?

**Comment by zookoatleastauthoritycom** [comment]
Is it because of their memory usage?

**Comment by ebfull** [comment]
That's what their documentation says apparently. :(

It would be nice if we used their new infrastructure which has fewer of these limitations, but they have to approve the libraries we use manually. They have not approved crypto++.

**Comment by daira** [comment]
Can't we install those libraries as the current user, without sudo?

**Comment by ebfull** [comment]
I don't remember why but I couldn't get the build to work at all with the library versions that travis had available to us. Either way the build of those libraries doesn't take much time.

**Comment by ebfull** [comment]
@daira you're right though, we shouldn't need sudo. I'll take another approach.

**Pull request closed without merging**
